---
- name: Deploy Spring Boot Application
  hosts: seed-hosts
  vars:
    ci_cd_namespace: labs-ci-cd
    dev_namespace: labs-dev
    test_namespace: labs-test
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier
