# This is the Ansible Galaxy requirements file to pull in the correct roles
# to support the operation of CASL provisioning/runs.

# From 'openshift-applier'
- src: https://github.com/redhat-cop/openshift-applier
  scm: git
  version: v2.1.2
  name: openshift-applier
