{{- if eq ( .Values.deploymentStrategy | default "non-prod" ) "non-prod" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "deploy-template.name" . }}-route
spec:
  host: "{{ .Values.host }}.apps.{{ .Values.cluster }}"
  to:
    kind: Service
    name: {{ include "deploy-template.fullname" . }}
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
