# This is the playbook will install a targeted set of 
- name: Create Projects and Policies
  hosts: bootstrap
  vars_files:
  - group_vars/all.yml
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier
      vars:
        filter_tags: projects,rolebinding-jenkins
        
- name: Create CI/CD tools
  hosts: tools
  vars_files:
  - group_vars/all.yml
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier
      tags:
        - openshift-applier
      vars:
        filter_tags: sonarqube,mvn-slave,nexus,jenkins 