# This is the Ansible Galaxy requirements file to pull in the correct roles
- src: https://github.com/rht-labs/labs-ci-cd
  scm: git
  version: v3.11.9
  name: labs-ci-cd
- src: https://github.com/redhat-cop/openshift-applier
  scm: git
  version: v2.1.1
  name: openshift-applier
